import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { cookies } from "next/headers";
import { ActiveThemeProvider } from "@/components/active-theme";
import ThemeProvider  from "@/components/providers/theme-providers";
import Footer from "@/components/Home/Footer/Footer";
import ScrollToTop from "@/components/Helper/ScrollToTop";

const font = Inter({
  weight:["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const activeThemeValue = cookieStore.get("active_theme")?.value;
  const isScaled = activeThemeValue?.endsWith("-scaled");
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body 
        className={cn(
          "bg-background overscroll-none font-sans antialiased",
          activeThemeValue ? `theme-${activeThemeValue}` : "",
          isScaled ? "theme-scaled" : "",
          font.className,
          "antialiased"
        )}
      >
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          enableColorScheme
        > */}
        <ThemeProvider>
          <ActiveThemeProvider initialTheme={activeThemeValue}>
            {children}
            <Footer/>
            <ScrollToTop />
          </ActiveThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
